name: jobs-deploy2
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.4=py38haa95532_0
  - matplotlib-base=3.3.4=py38h49ac443_0
  - nltk=3.6.2=pyhd3eb1b0_0
  - numpy=1.20.2=py38ha4e8547_0
  - numpy-base=1.20.2=py38hc2deb75_0
  - pandas=1.2.4=py38hd77b12b_0
  - python=3.8.10=hdbf39b2_7
  - scikit-learn=0.24.2=py38h5d5d464_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - wordcloud=1.8.1=py38h294d835_1
  - pip:
    - imbalanced-learn==0.8.0
    - pip==21.2.4
    - streamlit==0.88.0
prefix: C:\Users\adin7\.conda\envs\jobs-analysis
